---

.heliconia:
  image: docker.haltu.net/haltu/env/heliconia:latest

.bergenia:
  image: docker.haltu.net/haltu/env/bergenia:1-init-repo-based-on-latest-heliconia

before_script:
  - cp local_settings.py.tpl local_settings.py
  - echo "DEBUG = True" >> local_settings.py
  - echo "SITE_ID = 1" >> local_settings.py
  - echo "SECURE_SSL_REDIRECT = False" >> local_settings.py
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - python3 -m venv ../venv
  - source ../venv/bin/activate

services:
  - name: mdillon/postgis:9.1
    alias: postgresql
  - memcached:1.4.25
  - redis:3.0.6

variables:
  DJANGO_SETTINGS_MODULE: local_settings
  POSTGRES_DB: heliconia
  POSTGRES_PASSWORD: heliconia
  POSTGRES_USER: heliconia
  RABBITMQ_DEFAULT_VHOST: heliconia

stages:
  - build
  - test

.build_devel:
  stage: build
  script:
    - pwd
    - cat local_settings.py
    - pip3 install -r requirements.txt
    - python3 manage.py help

build_devel_heliconia:
  extends:
    - .build_devel
    - .heliconia

build_devel_bergenia:
  extends:
    - .build_devel
    - .bergenia

.build_prod:
  stage: build
  script:
    - pwd
    - cat local_settings.py
    - pip3 install -r requirements_prod.txt
    - python3 manage.py help

build_prod_heliconia:
  extends:
    - .build_prod
    - .heliconia

build_prod_bergenia:
  extends:
    - .build_prod
    - .bergenia

.prospector:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - prospector -0 --uses django .

prospector_heliconia:
  extends:
    - .prospector
    - .heliconia

prospector_bergenia:
  extends:
    - .prospector
    - .bergenia

.migrate:
  stage: test
  script:
    - pip3 install -r requirements_prod.txt
    - python3 manage.py migrate

migrate_heliconia:
  extends:
    - .migrate
    - .heliconia

migrate_bergenia:
  extends:
    - .migrate
    - .bergenia

.test:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - pytest

test_heliconia:
  extends:
    - .test
    - .heliconia

test_bergenia:
  extends:
    - .test
    - .bergenia

