---
image: docker.haltu.net/haltu/env/bergenia:latest

before_script:
  - cp local_settings.py.tpl local_settings.py
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - python3 -m venv ../venv
  - source ../venv/bin/activate
  - pip3 install wheel

services:
  - name: mdillon/postgis:10
    alias: postgresql
  - memcached:1.5.6
  - redis:4.0.9

variables:
  DJANGO_SETTINGS_MODULE: local_settings
  POSTGRES_DB: bergenia
  POSTGRES_PASSWORD: bergenia
  POSTGRES_USER: bergenia
  RABBITMQ_DEFAULT_VHOST: bergenia

stages:
  - build
  - test

build_devel:
  stage: build
  script:
    - pwd
    - cat local_settings.py
    - pip3 install -r requirements.txt
    - python3 manage.py help

build_prod:
  stage: build
  script:
    - pwd
    - cat local_settings.py
    - pip3 install -r requirements_prod.txt
    - python3 manage.py help

prospector:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - prospector -0 --uses django,celery src

migrate:
  stage: test
  script:
    - pip3 install -r requirements_prod.txt
    - python3 manage.py migrate

test:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - pytest
