---
image: docker.haltu.net/haltu/env/heliconia:latest

before_script:
  - cp /home/bew/local_settings.py local_settings.py
  - echo "DEBUG = True" >> local_settings.py
  - echo "SITE_ID = 1" >> local_settings.py
  - sed -i -r "s/^BROKER_URL/CELERY_BROKER_URL/g" local_settings.py
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

services:
  - name: postgres:9.1
    alias: postgresql
  - memcached:1.4.25
  - redis:3.0.6
  - rabbitmq:3.6.10

variables:
  DJANGO_SETTINGS_MODULE: local_settings
  POSTGRES_DB: heliconia
  POSTGRES_PASSWORD: heliconia
  POSTGRES_USER: heliconia
  RABBITMQ_DEFAULT_VHOST: heliconia

stages:
  - build
  - test

build_devel:
  stage: build
  script:
    - pwd
    - cat local_settings.py
    - buildout -c buildout.cfg
    - bin/django help

build_prod:
  stage: build
  script:
    - buildout -c production.cfg
    - bin/django help

prospector:
  stage: test
  script:
    - buildout -c buildout.cfg
    - bin/prospector -0 --uses django,celery src

migrate:
  stage: test
  script:
    - buildout -c production.cfg
    - bin/django migrate dreamuserdb
    - bin/django migrate

staticfiles:
  stage: test
  script:
    - buildout -c production.cfg
    - bin/django collectstatic --noinput -v 3 --traceback
    - bin/django compress -v 3 --traceback

test:
  stage: test
  script:
    - buildout -c buildout.cfg
    - bin/test

saucetest:
  stage: test
  script:
    - buildout -c buildout.cfg
    - bin/saucetest
