# Generated by Django 2.2 on 2019-07-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(1, 'Maanantai'), (2, 'Tiistai'), (3, 'Keskiviikko'), (4, 'Torstai'), (5, 'Perjantai'), (6, 'Lauantai'), (7, 'Sunnuntai')], null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hobby_images')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harrastuspassi.Location')),
            ],
        ),
    ]
