# Generated by Django 2.2 on 2019-08-08 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('harrastuspassi', '0003_add_dates_to_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='end_day_of_week',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='start_day_of_week',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='start_time',
        ),
        migrations.CreateModel(
            name='HobbyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='harrastuspassi.Hobby', verbose_name='Hobby')),
            ],
            options={
                'verbose_name': 'Hobby Event',
            },
        ),
    ]
