# Generated by Django 2.2 on 2019-08-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrastuspassi', '0004_hobbyevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobbyevent',
            options={'ordering': ('start_date', 'start_time'), 'verbose_name': 'Hobby Event'},
        ),
        migrations.AddField(
            model_name='hobbyevent',
            name='start_weekday',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Start weekday'),
        ),
    ]
