# Generated by Django 2.2 on 2019-08-28 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harrastuspassi', '0005_hobbyevent_start_weekday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobby',
            options={'get_latest_by': 'created_at', 'ordering': ('id',), 'verbose_name_plural': 'Hobbies'},
        ),
        migrations.AddField(
            model_name='hobby',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hobbyevent',
            name='start_weekday',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=0, verbose_name='Start weekday'),
        ),
    ]
