# Generated by Django 2.2.4 on 2019-10-09 12:04

from django.db import migrations, models


def copy_category(apps, schema_editor):
    Hobby = apps.get_model('harrastuspassi', 'Hobby')
    for hobby in Hobby.objects.all():
        if hobby.category:
            hobby.categories.add(hobby.category)


class Migration(migrations.Migration):

    dependencies = [
        ('harrastuspassi', '0007_external_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='hobbies', to='harrastuspassi.HobbyCategory', verbose_name='Categories'),
        ),
        migrations.RunPython(copy_category),
        migrations.RemoveField(
            model_name='hobby',
            name='category',
        ),
    ]
