# Generated by Django 2.2.4 on 2019-10-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrastuspassi', '0009_hobbycategory_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbycategory',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
