# Generated by Django 2.2.4 on 2019-11-11 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harrastuspassi', '0010_category_name_not_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('moderators', models.ManyToManyField(blank=True, related_name='municipalities_where_moderator', to=settings.AUTH_USER_MODEL, verbose_name='Moderators')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hobby',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harrastuspassi.Municipality'),
        ),
    ]
