# Generated by Django 2.2.4 on 2019-11-26 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('harrastuspassi', '0012_add_municipality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='hobby',
        ),
        migrations.AddField(
            model_name='promotion',
            name='available_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='harrastuspassi.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harrastuspassi.Municipality'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='harrastuspassi.Organizer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harrastuspassi.Promotion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
