# Generated by Django 2.2.4 on 2019-12-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrastuspassi', '0013_promotion_and_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='hobby',
            name='price_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('ANNUAL', 'Annual'), ('SEASONAL', 'Seasonal'), ('ONE_TIME', 'One time')], default='FREE', max_length=1024),
        ),
    ]
