# Generated by Django 2.2.4 on 2020-07-23 16:38

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('harrastuspassi', '0017_translate_hobbycategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Hobby'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='price_type',
            field=models.CharField(choices=[('free', 'Free'), ('annual', 'Annual'), ('seasonal', 'Seasonal'), ('one_time', 'One time')], default='free', max_length=1024, verbose_name='Price type'),
        ),
        migrations.AlterField(
            model_name='hobbycategory',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Hobby Category'),
        ),
        migrations.AlterField(
            model_name='hobbycategory',
            name='name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Hobby Category'),
        ),
        migrations.AlterField(
            model_name='hobbycategory',
            name='name_fi',
            field=models.CharField(max_length=256, null=True, verbose_name='Hobby Category'),
        ),
        migrations.AlterField(
            model_name='hobbycategory',
            name='name_sv',
            field=models.CharField(max_length=256, null=True, verbose_name='Hobby Category'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Organizer'),
        ),
        migrations.CreateModel(
            name='HobbyAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(blank=True, default='', max_length=256, verbose_name='External data source')),
                ('origin_id', models.CharField(blank=True, default='', max_length=128, verbose_name='ID in external data source')),
                ('name', models.CharField(max_length=256, verbose_name='Hobby Audience')),
                ('name_fi', models.CharField(max_length=256, null=True, verbose_name='Hobby Audience')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='Hobby Audience')),
                ('name_sv', models.CharField(max_length=256, null=True, verbose_name='Hobby Audience')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='harrastuspassi.HobbyAudience')),
            ],
            options={
                'verbose_name_plural': 'Hobby Audience',
            },
        ),
    ]
