# Generated by Django 2.2.4 on 2020-07-30 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('harrastuspassi', '0018_add_HobbyAudience'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='cover_image_modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
