# Generated by Django 2.2.4 on 2020-07-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrastuspassi', '0019_hobby_cover_image_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='price_type',
            field=models.CharField(choices=[('free', 'Free'), ('annual', 'Annual'), ('seasonal', 'Seasonal'), ('one_time', 'One time'), ('paid', 'Paid')], default='free', max_length=1024, verbose_name='Price type'),
        ),
    ]
