# Generated by Django 2.2.4 on 2020-08-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harrastuspassi', '0020_Add_Paid_Price_Type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbyevent',
            name='recurrence_start_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='harrastuspassi.HobbyEvent', verbose_name='Recurrence start event'),
        ),
    ]
