# Generated by Django 2.2.4 on 2020-08-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harrastuspassi', '0021_hobby_event_recurrence_start_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbyevent',
            name='hobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='harrastuspassi.Hobby', verbose_name='Hobby'),
        ),
    ]
