# Generated by Django 2.2.4 on 2021-05-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrastuspassi', '0022_hobby_next_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbycategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='hobbycategory_images'),
        ),
    ]
